### ISSUE TITLE
Can't find good font directory with flutter 3.3.10 

### ISSUE THREAD

**Issue by Remi-deronzier** [bamlab/adaptive_test#16]
# Describe the bug

First of all, thanks for the package.

Yet, it seems that there is a problem when loading fonts: the font directory is not the appropriate one in the `helper/fonts_loader.dart` file in the `loadFontsFromFontsDir` function.

```dart
/// Assumes a fonts dir in root of project
@visibleForTesting
Map<String, List<Future<ByteData>>> loadFontsFromFontsDir([String? package]) {
  final fontFamilyToData = <String, List<Future<ByteData>>>{};
  final currentDir = path.dirname(Platform.script.path);
  final fontsDirectory = path.join(
    currentDir,
    package == null ? 'fonts' : '../$package/fonts',
  );
  final prefix = package == null ? '' : 'packages/$package/';
  for (final file in Directory(fontsDirectory).listSync()) {
    if (file is File) {
      final fontFamily =
          prefix + path.basenameWithoutExtension(file.path).split('-').first;
      (fontFamilyToData[fontFamily] ??= [])
          .add(file.readAsBytes().then((bytes) => ByteData.view(bytes.buffer)));
    }
  }
  return fontFamilyToData;
}
```

In my case, my real `fontsDirectory` would be for example `User/remi/my-repo/theme/fonts/` instead `fontsDirectory` was `User/remi/my-repo/theme/./theme/fonts/`.

# Steps to reproduce

Use flutter version 3.3.10 and launch any test using the library `adaptive_test`

# What is the expected behavior?

In version 3.3.10, I should launch tests with `adaptive_test` without having to manually modified the `fontsDirectory` in `helper/fonts_loader.dart` file.

Thanks :)

**Comment by T-moz** [comment]
Fixed by: https://github.com/bamlab/adaptive_test/pull/15
